### ISSUE TITLE
"Could not connect to R session on RStudio server" error 

### ISSUE THREAD

**Issue by koegli** [Stephen-McDaniel/YakData-SmartDesktop-RStudio#2]
<img width="426" alt="Docker" src="https://user-images.githubusercontent.com/24729549/155718432-65bb4579-4810-4cc7-90c9-3a08ca79ef2a.png">

Followed all steps on an iMAC M1 and get this error message after launching localhost etc. in Safari or Chrome.

Any idea what's wrong?

Best,

Nicolaus

**Comment by Stephen-McDaniel** [comment]
Hi Nicolaus,

Please share:
1) More details of what worked preceding this. Do you see the RStudio screen when you visit localhost:4120?
![image](https://user-images.githubusercontent.com/9154079/158255325-096d61c7-6882-4c87-8364-8376fc700433.png)

2) A full screenshot when you see this message, for context.

And any other information to help me replicate your situation.

Thanks

**Comment by Stephen-McDaniel** [comment]
Closing due to lack of reply. Please reopen if I can be of assistance.
