### ISSUE TITLE
using 'rtweet' with SmartDesktop

### ISSUE THREAD

**Issue by Bretsy3121** [Stephen-McDaniel/YakData-SmartDesktop-RStudio#3]
Great package and so speedy.
BUT, I came to use rtweet to analyse twitter feeds and and came upon the problem of authorisation.
I was directed to the Twitter authorisation page and signed in ok, but on clicking authorise the page came up with an error saying it cannot re-direct back to the webpage that I originally came from (RStudio Desktop).
"This site can’t be reached127.0.0.1 refused to connect."

**Comment by Bretsy3121** [comment]
Hi. again,
Fixed the problem - I needed to reload the OATH keys into SmartDesktop and it now works.
Thanks again

**Comment by Stephen-McDaniel** [comment]
Cheers, please feel free to share other feedback/ideas!
