### ISSUE TITLE
Is there a way to install with singularity?

### ISSUE THREAD

**Issue by adrisede** [Stephen-McDaniel/YakData-SmartDesktop-RStudio#4]
I'd love to try out your container, but our HPC cluster does not allow docker to be used, only singularity. Is there a way to adapt this to work with  singularity? Thanks~!

**Comment by Stephen-McDaniel** [comment]
This would be a separate project. Will consider at a future release. 

The likely path for such a project appears to be in development: https://singularityhub.github.io/singularity-compose/#/
