### ISSUE TITLE
SmartDesktop and DockerDesktop

### ISSUE THREAD

**Issue by Bretsy3121** [Stephen-McDaniel/YakData-SmartDesktop-RStudio#5]
I cannot find anywhere the answer to my simple 2 questions.
What is the purpose of Docker in simple terms and does it need to be running all the time (when using SmartDesktop-RStudio)?
I am more interested in the answer to. the second question really.

**Comment by Stephen-McDaniel** [comment]
1) What is the purpose of using Docker: http://stackoverflow.com/questions/28089344/ddg#42111368 

2) Yes. 

In the /yakdata/apps/docker-compose.yml file, note I set it to “restart: unless-stopped”. So, unless you tell Docker to stop the container (once running) or unless you stop Docker Desktop or the Docker service, Docker will automatically restart the container if the container fails for some reason. 

This also means it will restart if you shut down and restart the host system, if you have set Docker Desktop to start on system login. https://docs.docker.com/desktop/mac/

**Comment by Bretsy3121** [comment]
Thank you - I am loving SmartDesktop by the way

**Comment by Stephen-McDaniel** [comment]
Thanks for the kind feedback!
