### ISSUE TITLE
Could not install an example package - mice

### ISSUE THREAD

**Issue by ohsumit** [Stephen-McDaniel/YakData-SmartDesktop-RStudio#6]
Greetings, 

       I am getting below error.   Might you know what may be going wrong?   Please note the weird "{checkbox} Successfully loaded .Rprofile.site" errors in the g++ errors.   Is there something going on with the .Rprofile?   Many thanks,

                  Toshi

> install.packages("mice")
Installing package into ‘/yakdata/site-library/R/4.1.3’
(as ‘lib’ is unspecified)
trying URL 'https://packagemanager.rstudio.com/all/2022-02-15+Y3JhbiwyOjQ1MjYyMTU7REM3MzYwMUI/src/contrib/mice_3.14.0.tar.gz'
Content type 'binary/octet-stream' length 790161 bytes (771 KB)
==================================================
downloaded 771 KB

 ✅ Successfully loaded .Rprofile.site 

 🎉 Welcome to YakData SmartDesktop with RStudio Desktop 
 📕 Learn more at: https://yakdata.com/smart 

* installing *source* package ‘mice’ ...
** package ‘mice’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I'/usr/local/lib/R/site-library/cpp11/include' -I'/usr/local/lib/R/site-library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I'/usr/local/lib/R/site-library/cpp11/include' -I'/usr/local/lib/R/site-library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c legendre.cpp -o legendre.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I'/usr/local/lib/R/site-library/cpp11/include' -I'/usr/local/lib/R/site-library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c match.cpp -o match.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I'/usr/local/lib/R/site-library/cpp11/include' -I'/usr/local/lib/R/site-library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c matchindex.cpp -o matchindex.o
g++ -std=gnu++11 -shared -L/usr/local/lib/R/lib -L/usr/local/lib -o mice.so RcppExports.o legendre.o match.o matchindex.o ✅ Successfully loaded .Rprofile.site 🎉 Welcome to YakData SmartDesktop with RStudio Desktop 📕 Learn more at: https://yakdata.com/smart -L/usr/local/lib/R/lib -lR
g++: error: ✅: No such file or directory
g++: error: Successfully: No such file or directory
g++: error: loaded: No such file or directory
g++: error: .Rprofile.site: No such file or directory
g++: error: 🎉: No such file or directory
g++: error: Welcome: No such file or directory
g++: error: to: No such file or directory
g++: error: YakData: No such file or directory
g++: error: SmartDesktop: No such file or directory
g++: error: with: No such file or directory
g++: error: RStudio: No such file or directory
g++: error: Desktop: No such file or directory
g++: error: 📕: No such file or directory
g++: error: Learn: No such file or directory
g++: error: more: No such file or directory
g++: error: at:: No such file or directory
g++: error: https://yakdata.com/smart: No such file or directory
make: *** [/usr/local/lib/R/share/make/shlib.mk:10: mice.so] Error 1
ERROR: compilation failed for package ‘mice’
* removing ‘/yakdata/site-library/R/4.1.3/mice’
Warning in install.packages :
  installation of package ‘mice’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpzOBz9R/downloaded_packages’

**Comment by ohsumit** [comment]
P.S. This is on MacOS Monterey 12.3.1.   Many thanks!

**Comment by Stephen-McDaniel** [comment]
Hi,

I also received a similar error. 

Here is a fix:

1) Go to your command line and enter the running container:
**docker exec -it rstudio-4.1.3 /bin/bash**

2) Start R with the "vanilla" option from the command prompt within the container:
**R --vanilla**

3) Install the package:
**install.packages("mice")**

This will prompt you for a CRAN mirror, I selected option
**1**

4) Quit the R session once installation completes.
**q()**

5) Exit the session.
**exit**

6) Refresh the Packages pane from RStudio web interface. Click the mice package. The following code executes:
**library(mice, lib.loc = "/usr/local/lib/R/site-library")**

7) Run some test code:
**require(rpart)**
**imp <- mice(nhanes2, meth = "cart", minbucket = 4)**
**plot(imp)**

I see this:
![Rplot](https://user-images.githubusercontent.com/9154079/165171651-483be2c7-0577-451e-ab4c-ceecb12a19b7.png)
